import 'package:learning_online/features/profile/data/user.dart';

final learnTopics =
[
  {
    "id": 3,
    "key": "english-for-kids",
    "name": "English for Kids",
    "createdAt": "2021-09-03T13:27:18.266Z",
    "updatedAt": "2021-09-03T13:27:18.266Z"
  },
  {
    "id": 4,
    "key": "business-english",
    "name": "Business English",
    "createdAt": "2021-09-03T13:27:18.266Z",
    "updatedAt": "2021-09-03T13:27:18.266Z"
  },
  {
    "id": 5,
    "key": "conversational-english",
    "name": "Conversational English",
    "createdAt": "2021-09-03T13:27:18.266Z",
    "updatedAt": "2021-09-03T13:27:18.266Z"
  }
].map((e) => LearnTopic.fromJson(e)).toList();

final tests = [
  {
    "id": 1,
    "key": "starters",
    "name": "STARTERS",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 2,
    "key": "movers",
    "name": "MOVERS",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 3,
    "key": "flyers",
    "name": "FLYERS",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 4,
    "key": "ket",
    "name": "KET",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 5,
    "key": "pet",
    "name": "PET",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 6,
    "key": "ielts",
    "name": "IELTS",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 7,
    "key": "toefl",
    "name": "TOEFL",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  },
  {
    "id": 8,
    "key": "toeic",
    "name": "TOEIC",
    "createdAt": "2021-09-03T13:27:18.820Z",
    "updatedAt": "2021-09-03T13:27:18.820Z"
  }
].map((e) => TestPreparation.fromJson(e)).toList();

final Map<String, String> levels = {
  'BEGINNER': 'Pre A1 (Beginner)',
  'HIGHER-BEGINNER': 'A1 (Higher Beginner',
  'PRE_INTERMEDIATE': 'A2 (Pre-Intermediate)',
  'INTERMEDIATE': 'B1 (Intermediate)',
  'UPPER-INTERMEDIATE': 'B2 (Upper-Intermediate)',
  'ADVANCED': 'C1 (Advanced)',
  'PROFICIENCY': 'C2 (Proficiency)',
};
final List<Map<String, String>> nations = [
  {
    "code": "AF",
    "name": "Afghanistan",
    "flag":
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png"
  },
  {"code": "AX", "name": "Åland Islands", "flag": "https://flagcdn.com/w320/ax.png"},
  {"code": "AL", "name": "Albania", "flag": "https://flagcdn.com/w320/al.png"},
  {"code": "DZ", "name": "Algeria", "flag": "https://flagcdn.com/w320/dz.png"},
  {"code": "AS", "name": "American Samoa", "flag": "https://flagcdn.com/w320/as.png"},
  {"code": "AD", "name": "Andorra", "flag": "https://flagcdn.com/w320/ad.png"},
  {"code": "AO", "name": "Angola", "flag": "https://flagcdn.com/w320/ao.png"},
  {"code": "AI", "name": "Anguilla", "flag": "https://flagcdn.com/w320/ai.png"},
  {"code": "AQ", "name": "Antarctica", "flag": "https://flagcdn.com/w320/aq.png"},
  {"code": "AG", "name": "Antigua and Barbuda", "flag": "https://flagcdn.com/w320/ag.png"},
  {"code": "AR", "name": "Argentina", "flag": "https://flagcdn.com/w320/ar.png"},
  {"code": "AM", "name": "Armenia", "flag": "https://flagcdn.com/w320/am.png"},
  {"code": "AW", "name": "Aruba", "flag": "https://flagcdn.com/w320/aw.png"},
  {"code": "AU", "name": "Australia", "flag": "https://flagcdn.com/w320/au.png"},
  {"code": "AT", "name": "Austria", "flag": "https://flagcdn.com/w320/at.png"},
  {"code": "AZ", "name": "Azerbaijan", "flag": "https://flagcdn.com/w320/az.png"},
  {"code": "BS", "name": "Bahamas", "flag": "https://flagcdn.com/w320/bs.png"},
  {"code": "BH", "name": "Bahrain", "flag": "https://flagcdn.com/w320/bh.png"},
  {"code": "BD", "name": "Bangladesh", "flag": "https://flagcdn.com/w320/bd.png"},
  {"code": "BB", "name": "Barbados", "flag": "https://flagcdn.com/w320/bb.png"},
  {"code": "BY", "name": "Belarus", "flag": "https://flagcdn.com/w320/by.png"},
  {"code": "BE", "name": "Belgium", "flag": "https://flagcdn.com/w320/be.png"},
  {"code": "BZ", "name": "Belize", "flag": "https://flagcdn.com/w320/bz.png"},
  {"code": "BJ", "name": "Benin", "flag": "https://flagcdn.com/w320/bj.png"},
  {"code": "BM", "name": "Bermuda", "flag": "https://flagcdn.com/w320/bm.png"},
  {"code": "BT", "name": "Bhutan", "flag": "https://flagcdn.com/w320/bt.png"},
  {
    "code": "BO",
    "name": "Bolivia (Plurinational State of)",
    "flag": "https://flagcdn.com/w320/bo.png"
  },
  {
    "code": "BQ",
    "name": "Bonaire, Sint Eustatius and Saba",
    "flag": "https://flagcdn.com/w320/bq.png"
  },
  {"code": "BA", "name": "Bosnia and Herzegovina", "flag": "https://flagcdn.com/w320/ba.png"},
  {"code": "BW", "name": "Botswana", "flag": "https://flagcdn.com/w320/bw.png"},
  {"code": "BV", "name": "Bouvet Island", "flag": "https://flagcdn.com/w320/bv.png"},
  {"code": "BR", "name": "Brazil", "flag": "https://flagcdn.com/w320/br.png"},
  {
    "code": "IO",
    "name": "British Indian Ocean Territory",
    "flag": "https://flagcdn.com/w320/io.png"
  },
  {
    "code": "UM",
    "name": "United States Minor Outlying Islands",
    "flag": "https://flagcdn.com/w320/um.png"
  },
  {"code": "VG", "name": "Virgin Islands (British)", "flag": "https://flagcdn.com/w320/vg.png"},
  {"code": "VI", "name": "Virgin Islands (U.S.)", "flag": "https://flagcdn.com/w320/vi.png"},
  {"code": "BN", "name": "Brunei Darussalam", "flag": "https://flagcdn.com/w320/bn.png"},
  {"code": "BG", "name": "Bulgaria", "flag": "https://flagcdn.com/w320/bg.png"},
  {"code": "BF", "name": "Burkina Faso", "flag": "https://flagcdn.com/w320/bf.png"},
  {"code": "BI", "name": "Burundi", "flag": "https://flagcdn.com/w320/bi.png"},
  {"code": "KH", "name": "Cambodia", "flag": "https://flagcdn.com/w320/kh.png"},
  {"code": "CM", "name": "Cameroon", "flag": "https://flagcdn.com/w320/cm.png"},
  {"code": "CA", "name": "Canada", "flag": "https://flagcdn.com/w320/ca.png"},
  {"code": "CV", "name": "Cabo Verde", "flag": "https://flagcdn.com/w320/cv.png"},
  {"code": "KY", "name": "Cayman Islands", "flag": "https://flagcdn.com/w320/ky.png"},
  {"code": "CF", "name": "Central African Republic", "flag": "https://flagcdn.com/w320/cf.png"},
  {"code": "TD", "name": "Chad", "flag": "https://flagcdn.com/w320/td.png"},
  {"code": "CL", "name": "Chile", "flag": "https://flagcdn.com/w320/cl.png"},
  {"code": "CN", "name": "China", "flag": "https://flagcdn.com/w320/cn.png"},
  {"code": "CX", "name": "Christmas Island", "flag": "https://flagcdn.com/w320/cx.png"},
  {"code": "CC", "name": "Cocos (Keeling) Islands", "flag": "https://flagcdn.com/w320/cc.png"},
  {"code": "CO", "name": "Colombia", "flag": "https://flagcdn.com/w320/co.png"},
  {"code": "KM", "name": "Comoros", "flag": "https://flagcdn.com/w320/km.png"},
  {"code": "CG", "name": "Congo", "flag": "https://flagcdn.com/w320/cg.png"},
  {
    "code": "CD",
    "name": "Congo (Democratic Republic of the)",
    "flag": "https://flagcdn.com/w320/cd.png"
  },
  {"code": "CK", "name": "Cook Islands", "flag": "https://flagcdn.com/w320/ck.png"},
  {"code": "CR", "name": "Costa Rica", "flag": "https://flagcdn.com/w320/cr.png"},
  {"code": "HR", "name": "Croatia", "flag": "https://flagcdn.com/w320/hr.png"},
  {"code": "CU", "name": "Cuba", "flag": "https://flagcdn.com/w320/cu.png"},
  {"code": "CW", "name": "Curaçao", "flag": "https://flagcdn.com/w320/cw.png"},
  {"code": "CY", "name": "Cyprus", "flag": "https://flagcdn.com/w320/cy.png"},
  {"code": "CZ", "name": "Czech Republic", "flag": "https://flagcdn.com/w320/cz.png"},
  {"code": "DK", "name": "Denmark", "flag": "https://flagcdn.com/w320/dk.png"},
  {"code": "DJ", "name": "Djibouti", "flag": "https://flagcdn.com/w320/dj.png"},
  {"code": "DM", "name": "Dominica", "flag": "https://flagcdn.com/w320/dm.png"},
  {"code": "DO", "name": "Dominican Republic", "flag": "https://flagcdn.com/w320/do.png"},
  {"code": "EC", "name": "Ecuador", "flag": "https://flagcdn.com/w320/ec.png"},
  {"code": "EG", "name": "Egypt", "flag": "https://flagcdn.com/w320/eg.png"},
  {"code": "SV", "name": "El Salvador", "flag": "https://flagcdn.com/w320/sv.png"},
  {"code": "GQ", "name": "Equatorial Guinea", "flag": "https://flagcdn.com/w320/gq.png"},
  {"code": "ER", "name": "Eritrea", "flag": "https://flagcdn.com/w320/er.png"},
  {"code": "EE", "name": "Estonia", "flag": "https://flagcdn.com/w320/ee.png"},
  {"code": "ET", "name": "Ethiopia", "flag": "https://flagcdn.com/w320/et.png"},
  {"code": "FK", "name": "Falkland Islands (Malvinas)", "flag": "https://flagcdn.com/w320/fk.png"},
  {"code": "FO", "name": "Faroe Islands", "flag": "https://flagcdn.com/w320/fo.png"},
  {"code": "FJ", "name": "Fiji", "flag": "https://flagcdn.com/w320/fj.png"},
  {"code": "FI", "name": "Finland", "flag": "https://flagcdn.com/w320/fi.png"},
  {"code": "FR", "name": "France", "flag": "https://flagcdn.com/w320/fr.png"},
  {"code": "GF", "name": "French Guiana", "flag": "https://flagcdn.com/w320/gf.png"},
  {"code": "PF", "name": "French Polynesia", "flag": "https://flagcdn.com/w320/pf.png"},
  {"code": "TF", "name": "French Southern Territories", "flag": "https://flagcdn.com/w320/tf.png"},
  {"code": "GA", "name": "Gabon", "flag": "https://flagcdn.com/w320/ga.png"},
  {"code": "GM", "name": "Gambia", "flag": "https://flagcdn.com/w320/gm.png"},
  {"code": "GE", "name": "Georgia", "flag": "https://flagcdn.com/w320/ge.png"},
  {"code": "DE", "name": "Germany", "flag": "https://flagcdn.com/w320/de.png"},
  {"code": "GH", "name": "Ghana", "flag": "https://flagcdn.com/w320/gh.png"},
  {"code": "GI", "name": "Gibraltar", "flag": "https://flagcdn.com/w320/gi.png"},
  {"code": "GR", "name": "Greece", "flag": "https://flagcdn.com/w320/gr.png"},
  {"code": "GL", "name": "Greenland", "flag": "https://flagcdn.com/w320/gl.png"},
  {"code": "GD", "name": "Grenada", "flag": "https://flagcdn.com/w320/gd.png"},
  {"code": "GP", "name": "Guadeloupe", "flag": "https://flagcdn.com/w320/gp.png"},
  {"code": "GU", "name": "Guam", "flag": "https://flagcdn.com/w320/gu.png"},
  {"code": "GT", "name": "Guatemala", "flag": "https://flagcdn.com/w320/gt.png"},
  {"code": "GG", "name": "Guernsey", "flag": "https://flagcdn.com/w320/gg.png"},
  {"code": "GN", "name": "Guinea", "flag": "https://flagcdn.com/w320/gn.png"},
  {"code": "GW", "name": "Guinea-Bissau", "flag": "https://flagcdn.com/w320/gw.png"},
  {"code": "GY", "name": "Guyana", "flag": "https://flagcdn.com/w320/gy.png"},
  {"code": "HT", "name": "Haiti", "flag": "https://flagcdn.com/w320/ht.png"},
  {
    "code": "HM",
    "name": "Heard Island and McDonald Islands",
    "flag": "https://flagcdn.com/w320/hm.png"
  },
  {"code": "VA", "name": "Vatican City", "flag": "https://flagcdn.com/w320/va.png"},
  {"code": "HN", "name": "Honduras", "flag": "https://flagcdn.com/w320/hn.png"},
  {"code": "HU", "name": "Hungary", "flag": "https://flagcdn.com/w320/hu.png"},
  {"code": "HK", "name": "Hong Kong", "flag": "https://flagcdn.com/w320/hk.png"},
  {"code": "IS", "name": "Iceland", "flag": "https://flagcdn.com/w320/is.png"},
  {"code": "IN", "name": "India", "flag": "https://flagcdn.com/w320/in.png"},
  {"code": "ID", "name": "Indonesia", "flag": "https://flagcdn.com/w320/id.png"},
  {"code": "CI", "name": "Ivory Coast", "flag": "https://flagcdn.com/w320/ci.png"},
  {"code": "IR", "name": "Iran (Islamic Republic of)", "flag": "https://flagcdn.com/w320/ir.png"},
  {"code": "IQ", "name": "Iraq", "flag": "https://flagcdn.com/w320/iq.png"},
  {"code": "IE", "name": "Ireland", "flag": "https://flagcdn.com/w320/ie.png"},
  {"code": "IM", "name": "Isle of Man", "flag": "https://flagcdn.com/w320/im.png"},
  {"code": "IL", "name": "Israel", "flag": "https://flagcdn.com/w320/il.png"},
  {"code": "IT", "name": "Italy", "flag": "https://flagcdn.com/w320/it.png"},
  {"code": "JM", "name": "Jamaica", "flag": "https://flagcdn.com/w320/jm.png"},
  {"code": "JP", "name": "Japan", "flag": "https://flagcdn.com/w320/jp.png"},
  {"code": "JE", "name": "Jersey", "flag": "https://flagcdn.com/w320/je.png"},
  {"code": "JO", "name": "Jordan", "flag": "https://flagcdn.com/w320/jo.png"},
  {"code": "KZ", "name": "Kazakhstan", "flag": "https://flagcdn.com/w320/kz.png"},
  {"code": "KE", "name": "Kenya", "flag": "https://flagcdn.com/w320/ke.png"},
  {"code": "KI", "name": "Kiribati", "flag": "https://flagcdn.com/w320/ki.png"},
  {"code": "KW", "name": "Kuwait", "flag": "https://flagcdn.com/w320/kw.png"},
  {"code": "KG", "name": "Kyrgyzstan", "flag": "https://flagcdn.com/w320/kg.png"},
  {
    "code": "LA",
    "name": "Lao People's Democratic Republic",
    "flag": "https://flagcdn.com/w320/la.png"
  },
  {"code": "LV", "name": "Latvia", "flag": "https://flagcdn.com/w320/lv.png"},
  {"code": "LB", "name": "Lebanon", "flag": "https://flagcdn.com/w320/lb.png"},
  {"code": "LS", "name": "Lesotho", "flag": "https://flagcdn.com/w320/ls.png"},
  {"code": "LR", "name": "Liberia", "flag": "https://flagcdn.com/w320/lr.png"},
  {"code": "LY", "name": "Libya", "flag": "https://flagcdn.com/w320/ly.png"},
  {"code": "LI", "name": "Liechtenstein", "flag": "https://flagcdn.com/w320/li.png"},
  {"code": "LT", "name": "Lithuania", "flag": "https://flagcdn.com/w320/lt.png"},
  {"code": "LU", "name": "Luxembourg", "flag": "https://flagcdn.com/w320/lu.png"},
  {"code": "MO", "name": "Macao", "flag": "https://flagcdn.com/w320/mo.png"},
  {"code": "MK", "name": "North Macedonia", "flag": "https://flagcdn.com/w320/mk.png"},
  {"code": "MG", "name": "Madagascar", "flag": "https://flagcdn.com/w320/mg.png"},
  {"code": "MW", "name": "Malawi", "flag": "https://flagcdn.com/w320/mw.png"},
  {"code": "MY", "name": "Malaysia", "flag": "https://flagcdn.com/w320/my.png"},
  {"code": "MV", "name": "Maldives", "flag": "https://flagcdn.com/w320/mv.png"},
  {"code": "ML", "name": "Mali", "flag": "https://flagcdn.com/w320/ml.png"},
  {"code": "MT", "name": "Malta", "flag": "https://flagcdn.com/w320/mt.png"},
  {"code": "MH", "name": "Marshall Islands", "flag": "https://flagcdn.com/w320/mh.png"},
  {"code": "MQ", "name": "Martinique", "flag": "https://flagcdn.com/w320/mq.png"},
  {"code": "MR", "name": "Mauritania", "flag": "https://flagcdn.com/w320/mr.png"},
  {"code": "MU", "name": "Mauritius", "flag": "https://flagcdn.com/w320/mu.png"},
  {"code": "YT", "name": "Mayotte", "flag": "https://flagcdn.com/w320/yt.png"},
  {"code": "MX", "name": "Mexico", "flag": "https://flagcdn.com/w320/mx.png"},
  {
    "code": "FM",
    "name": "Micronesia (Federated States of)",
    "flag": "https://flagcdn.com/w320/fm.png"
  },
  {"code": "MD", "name": "Moldova (Republic of)", "flag": "https://flagcdn.com/w320/md.png"},
  {"code": "MC", "name": "Monaco", "flag": "https://flagcdn.com/w320/mc.png"},
  {"code": "MN", "name": "Mongolia", "flag": "https://flagcdn.com/w320/mn.png"},
  {"code": "ME", "name": "Montenegro", "flag": "https://flagcdn.com/w320/me.png"},
  {"code": "MS", "name": "Montserrat", "flag": "https://flagcdn.com/w320/ms.png"},
  {"code": "MA", "name": "Morocco", "flag": "https://flagcdn.com/w320/ma.png"},
  {"code": "MZ", "name": "Mozambique", "flag": "https://flagcdn.com/w320/mz.png"},
  {"code": "MM", "name": "Myanmar", "flag": "https://flagcdn.com/w320/mm.png"},
  {"code": "NA", "name": "Namibia", "flag": "https://flagcdn.com/w320/na.png"},
  {"code": "NR", "name": "Nauru", "flag": "https://flagcdn.com/w320/nr.png"},
  {"code": "NP", "name": "Nepal", "flag": "https://flagcdn.com/w320/np.png"},
  {"code": "NL", "name": "Netherlands", "flag": "https://flagcdn.com/w320/nl.png"},
  {"code": "NC", "name": "New Caledonia", "flag": "https://flagcdn.com/w320/nc.png"},
  {"code": "NZ", "name": "New Zealand", "flag": "https://flagcdn.com/w320/nz.png"},
  {"code": "NI", "name": "Nicaragua", "flag": "https://flagcdn.com/w320/ni.png"},
  {"code": "NE", "name": "Niger", "flag": "https://flagcdn.com/w320/ne.png"},
  {"code": "NG", "name": "Nigeria", "flag": "https://flagcdn.com/w320/ng.png"},
  {"code": "NU", "name": "Niue", "flag": "https://flagcdn.com/w320/nu.png"},
  {"code": "NF", "name": "Norfolk Island", "flag": "https://flagcdn.com/w320/nf.png"},
  {
    "code": "KP",
    "name": "Korea (Democratic People's Republic of)",
    "flag": "https://flagcdn.com/w320/kp.png"
  },
  {"code": "MP", "name": "Northern Mariana Islands", "flag": "https://flagcdn.com/w320/mp.png"},
  {"code": "NO", "name": "Norway", "flag": "https://flagcdn.com/w320/no.png"},
  {"code": "OM", "name": "Oman", "flag": "https://flagcdn.com/w320/om.png"},
  {"code": "PK", "name": "Pakistan", "flag": "https://flagcdn.com/w320/pk.png"},
  {"code": "PW", "name": "Palau", "flag": "https://flagcdn.com/w320/pw.png"},
  {"code": "PS", "name": "Palestine, State of", "flag": "https://flagcdn.com/w320/ps.png"},
  {"code": "PA", "name": "Panama", "flag": "https://flagcdn.com/w320/pa.png"},
  {"code": "PG", "name": "Papua New Guinea", "flag": "https://flagcdn.com/w320/pg.png"},
  {"code": "PY", "name": "Paraguay", "flag": "https://flagcdn.com/w320/py.png"},
  {"code": "PE", "name": "Peru", "flag": "https://flagcdn.com/w320/pe.png"},
  {"code": "PH", "name": "Philippines", "flag": "https://flagcdn.com/w320/ph.png"},
  {"code": "PN", "name": "Pitcairn", "flag": "https://flagcdn.com/w320/pn.png"},
  {"code": "PL", "name": "Poland", "flag": "https://flagcdn.com/w320/pl.png"},
  {"code": "PT", "name": "Portugal", "flag": "https://flagcdn.com/w320/pt.png"},
  {"code": "PR", "name": "Puerto Rico", "flag": "https://flagcdn.com/w320/pr.png"},
  {"code": "QA", "name": "Qatar", "flag": "https://flagcdn.com/w320/qa.png"},
  {"code": "XK", "name": "Republic of Kosovo", "flag": "https://flagcdn.com/w320/xk.png"},
  {"code": "RE", "name": "Réunion", "flag": "https://flagcdn.com/w320/re.png"},
  {"code": "RO", "name": "Romania", "flag": "https://flagcdn.com/w320/ro.png"},
  {"code": "RU", "name": "Russian Federation", "flag": "https://flagcdn.com/w320/ru.png"},
  {"code": "RW", "name": "Rwanda", "flag": "https://flagcdn.com/w320/rw.png"},
  {"code": "BL", "name": "Saint Barthélemy", "flag": "https://flagcdn.com/w320/bl.png"},
  {
    "code": "SH",
    "name": "Saint Helena, Ascension and Tristan da Cunha",
    "flag": "https://flagcdn.com/w320/sh.png"
  },
  {"code": "KN", "name": "Saint Kitts and Nevis", "flag": "https://flagcdn.com/w320/kn.png"},
  {"code": "LC", "name": "Saint Lucia", "flag": "https://flagcdn.com/w320/lc.png"},
  {"code": "MF", "name": "Saint Martin (French part)", "flag": "https://flagcdn.com/w320/mf.png"},
  {"code": "PM", "name": "Saint Pierre and Miquelon", "flag": "https://flagcdn.com/w320/pm.png"},
  {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "flag": "https://flagcdn.com/w320/vc.png"
  },
  {"code": "WS", "name": "Samoa", "flag": "https://flagcdn.com/w320/ws.png"},
  {"code": "SM", "name": "San Marino", "flag": "https://flagcdn.com/w320/sm.png"},
  {"code": "ST", "name": "Sao Tome and Principe", "flag": "https://flagcdn.com/w320/st.png"},
  {"code": "SA", "name": "Saudi Arabia", "flag": "https://flagcdn.com/w320/sa.png"},
  {"code": "SN", "name": "Senegal", "flag": "https://flagcdn.com/w320/sn.png"},
  {"code": "RS", "name": "Serbia", "flag": "https://flagcdn.com/w320/rs.png"},
  {"code": "SC", "name": "Seychelles", "flag": "https://flagcdn.com/w320/sc.png"},
  {"code": "SL", "name": "Sierra Leone", "flag": "https://flagcdn.com/w320/sl.png"},
  {"code": "SG", "name": "Singapore", "flag": "https://flagcdn.com/w320/sg.png"},
  {"code": "SX", "name": "Sint Maarten (Dutch part)", "flag": "https://flagcdn.com/w320/sx.png"},
  {"code": "SK", "name": "Slovakia", "flag": "https://flagcdn.com/w320/sk.png"},
  {"code": "SI", "name": "Slovenia", "flag": "https://flagcdn.com/w320/si.png"},
  {"code": "SB", "name": "Solomon Islands", "flag": "https://flagcdn.com/w320/sb.png"},
  {"code": "SO", "name": "Somalia", "flag": "https://flagcdn.com/w320/so.png"},
  {"code": "ZA", "name": "South Africa", "flag": "https://flagcdn.com/w320/za.png"},
  {
    "code": "GS",
    "name": "South Georgia and the South Sandwich Islands",
    "flag": "https://flagcdn.com/w320/gs.png"
  },
  {"code": "KR", "name": "Korea (Republic of)", "flag": "https://flagcdn.com/w320/kr.png"},
  {"code": "ES", "name": "Spain", "flag": "https://flagcdn.com/w320/es.png"},
  {"code": "LK", "name": "Sri Lanka", "flag": "https://flagcdn.com/w320/lk.png"},
  {"code": "SD", "name": "Sudan", "flag": "https://flagcdn.com/w320/sd.png"},
  {"code": "SS", "name": "South Sudan", "flag": "https://flagcdn.com/w320/ss.png"},
  {"code": "SR", "name": "Suriname", "flag": "https://flagcdn.com/w320/sr.png"},
  {"code": "SJ", "name": "Svalbard and Jan Mayen", "flag": "https://flagcdn.com/w320/sj.png"},
  {"code": "SZ", "name": "Swaziland", "flag": "https://flagcdn.com/w320/sz.png"},
  {"code": "SE", "name": "Sweden", "flag": "https://flagcdn.com/w320/se.png"},
  {"code": "CH", "name": "Switzerland", "flag": "https://flagcdn.com/w320/ch.png"},
  {"code": "SY", "name": "Syrian Arab Republic", "flag": "https://flagcdn.com/w320/sy.png"},
  {"code": "TW", "name": "Taiwan", "flag": "https://flagcdn.com/w320/tw.png"},
  {"code": "TJ", "name": "Tajikistan", "flag": "https://flagcdn.com/w320/tj.png"},
  {"code": "TZ", "name": "Tanzania, United Republic of", "flag": "https://flagcdn.com/w320/tz.png"},
  {"code": "TH", "name": "Thailand", "flag": "https://flagcdn.com/w320/th.png"},
  {"code": "TL", "name": "Timor-Leste", "flag": "https://flagcdn.com/w320/tl.png"},
  {"code": "TG", "name": "Togo", "flag": "https://flagcdn.com/w320/tg.png"},
  {"code": "TK", "name": "Tokelau", "flag": "https://flagcdn.com/w320/tk.png"},
  {"code": "TO", "name": "Tonga", "flag": "https://flagcdn.com/w320/to.png"},
  {"code": "TT", "name": "Trinidad and Tobago", "flag": "https://flagcdn.com/w320/tt.png"},
  {"code": "TN", "name": "Tunisia", "flag": "https://flagcdn.com/w320/tn.png"},
  {"code": "TR", "name": "Turkey", "flag": "https://flagcdn.com/w320/tr.png"},
  {"code": "TM", "name": "Turkmenistan", "flag": "https://flagcdn.com/w320/tm.png"},
  {"code": "TC", "name": "Turks and Caicos Islands", "flag": "https://flagcdn.com/w320/tc.png"},
  {"code": "TV", "name": "Tuvalu", "flag": "https://flagcdn.com/w320/tv.png"},
  {"code": "UG", "name": "Uganda", "flag": "https://flagcdn.com/w320/ug.png"},
  {"code": "UA", "name": "Ukraine", "flag": "https://flagcdn.com/w320/ua.png"},
  {"code": "AE", "name": "United Arab Emirates", "flag": "https://flagcdn.com/w320/ae.png"},
  {
    "code": "GB",
    "name": "United Kingdom of Great Britain and Northern Ireland",
    "flag": "https://flagcdn.com/w320/gb.png"
  },
  {"code": "US", "name": "United States of America", "flag": "https://flagcdn.com/w320/us.png"},
  {"code": "UY", "name": "Uruguay", "flag": "https://flagcdn.com/w320/uy.png"},
  {"code": "UZ", "name": "Uzbekistan", "flag": "https://flagcdn.com/w320/uz.png"},
  {"code": "VU", "name": "Vanuatu", "flag": "https://flagcdn.com/w320/vu.png"},
  {
    "code": "VE",
    "name": "Venezuela (Bolivarian Republic of)",
    "flag": "https://flagcdn.com/w320/ve.png"
  },
  {"code": "VN", "name": "Vietnam", "flag": "https://flagcdn.com/w320/vn.png"},
  {"code": "WF", "name": "Wallis and Futuna", "flag": "https://flagcdn.com/w320/wf.png"},
  {"code": "EH", "name": "Western Sahara", "flag": "https://flagcdn.com/w320/eh.png"},
  {"code": "YE", "name": "Yemen", "flag": "https://flagcdn.com/w320/ye.png"},
  {"code": "ZM", "name": "Zambia", "flag": "https://flagcdn.com/w320/zm.png"},
  {"code": "ZW", "name": "Zimbabwe", "flag": "https://flagcdn.com/w320/zw.png"}
];

final languages = [
  {"code": "ps", "iso639_2": "pus", "name": "Pashto", "nativeName": "پښتو"},
  {"code": "uz", "iso639_2": "uzb", "name": "Uzbek", "nativeName": "Oʻzbek"},
  {"code": "tk", "iso639_2": "tuk", "name": "Turkmen", "nativeName": "Türkmen"},
  {"code": "sv", "iso639_2": "swe", "name": "Swedish", "nativeName": "svenska"},
  {"code": "sq", "iso639_2": "sqi", "name": "Albanian", "nativeName": "Shqip"},
  {"code": "ar", "iso639_2": "ara", "name": "Arabic", "nativeName": "العربية"},
  {"code": "en", "iso639_2": "eng", "name": "English", "nativeName": "English"},
  {"code": "sm", "iso639_2": "smo", "name": "Samoan", "nativeName": "gagana fa'a Samoa"},
  {"code": "ca", "iso639_2": "cat", "name": "Catalan", "nativeName": "català"},
  {"code": "pt", "iso639_2": "por", "name": "Portuguese", "nativeName": "Português"},
  {"code": "ru", "iso639_2": "rus", "name": "Russian", "nativeName": "Русский"},
  {"code": "es", "iso639_2": "spa", "name": "Spanish", "nativeName": "Español"},
  {"code": "gn", "iso639_2": "grn", "name": "Guaraní", "nativeName": "Avañe'ẽ"},
  {"code": "hy", "iso639_2": "hye", "name": "Armenian", "nativeName": "Հայերեն"},
  {"code": "nl", "iso639_2": "nld", "name": "Dutch", "nativeName": "Nederlands"},
  {"code": "pa", "iso639_2": "pan", "name": "(Eastern) Punjabi", "nativeName": "ਪੰਜਾਬੀ"},
  {"code": "de", "iso639_2": "deu", "name": "German", "nativeName": "Deutsch"},
  {"code": "az", "iso639_2": "aze", "name": "Azerbaijani", "nativeName": "azərbaycan dili"},
  {"code": "bn", "iso639_2": "ben", "name": "Bengali", "nativeName": "বাংলা"},
  {"code": "be", "iso639_2": "bel", "name": "Belarusian", "nativeName": "беларуская мова"},
  {"code": "fr", "iso639_2": "fra", "name": "French", "nativeName": "français"},
  {"code": "dz", "iso639_2": "dzo", "name": "Dzongkha", "nativeName": "རྫོང་ཁ"},
  {"code": "ay", "iso639_2": "aym", "name": "Aymara", "nativeName": "aymar aru"},
  {"code": "qu", "iso639_2": "que", "name": "Quechua", "nativeName": "Runa Simi"},
  {"code": "bs", "iso639_2": "bos", "name": "Bosnian", "nativeName": "bosanski jezik"},
  {"code": "hr", "iso639_2": "hrv", "name": "Croatian", "nativeName": "hrvatski jezik"},
  {"code": "sr", "iso639_2": "srp", "name": "Serbian", "nativeName": "српски језик"},
  {"code": "tn", "iso639_2": "tsn", "name": "Tswana", "nativeName": "Setswana"},
  {"code": "no", "iso639_2": "nor", "name": "Norwegian", "nativeName": "Norsk"},
  {"code": "nb", "iso639_2": "nob", "name": "Norwegian Bokmål", "nativeName": "Norsk bokmål"},
  {"code": "nn", "iso639_2": "nno", "name": "Norwegian Nynorsk", "nativeName": "Norsk nynorsk"},
  {"code": "ms", "iso639_2": "msa", "name": "Malay", "nativeName": "bahasa Melayu"},
  {"code": "bg", "iso639_2": "bul", "name": "Bulgarian", "nativeName": "български език"},
  {"code": "ff", "iso639_2": "ful", "name": "Fula", "nativeName": "Fulfulde"},
  {"code": "rn", "iso639_2": "run", "name": "Kirundi", "nativeName": "Ikirundi"},
  {"code": "km", "iso639_2": "khm", "name": "Khmer", "nativeName": "ខ្មែរ"},
  {"code": "sg", "iso639_2": "sag", "name": "Sango", "nativeName": "yângâ tî sängö"},
  {"code": "zh", "iso639_2": "zho", "name": "Chinese", "nativeName": "中文 (Zhōngwén)"},
  {"code": "ln", "iso639_2": "lin", "name": "Lingala", "nativeName": "Lingála"},
  {"code": "kg", "iso639_2": "kon", "name": "Kongo", "nativeName": "Kikongo"},
  {"code": "sw", "iso639_2": "swa", "name": "Swahili", "nativeName": "Kiswahili"},
  {"code": "lu", "iso639_2": "lub", "name": "Luba-Katanga", "nativeName": "Tshiluba"},
  {"iso639_2": "rar", "name": "Cook Islands Māori", "nativeName": "Māori"},
  {"code": "el", "iso639_2": "ell", "name": "Greek (modern)", "nativeName": "ελληνικά"},
  {"code": "tr", "iso639_2": "tur", "name": "Turkish", "nativeName": "Türkçe"},
  {"code": "cs", "iso639_2": "ces", "name": "Czech", "nativeName": "čeština"},
  {"code": "sk", "iso639_2": "slk", "name": "Slovak", "nativeName": "slovenčina"},
  {"code": "da", "iso639_2": "dan", "name": "Danish", "nativeName": "dansk"},
  {"code": "ti", "iso639_2": "tir", "name": "Tigrinya", "nativeName": "ትግርኛ"},
  {"code": "aa", "iso639_2": "aar", "name": "Afar", "nativeName": "Afar"},
  {"code": "et", "iso639_2": "est", "name": "Estonian", "nativeName": "eesti"},
  {"code": "am", "iso639_2": "amh", "name": "Amharic", "nativeName": "አማርኛ"},
  {"code": "fo", "iso639_2": "fao", "name": "Faroese", "nativeName": "føroyskt"},
  {"code": "fj", "iso639_2": "fij", "name": "Fijian", "nativeName": "vosa Vakaviti"},
  {"code": "fi", "iso639_2": "fin", "name": "Finnish", "nativeName": "suomi"},
  {"code": "ka", "iso639_2": "kat", "name": "Georgian", "nativeName": "ქართული"},
  {"code": "kl", "iso639_2": "kal", "name": "Kalaallisut", "nativeName": "kalaallisut"},
  {"code": "ch", "iso639_2": "cha", "name": "Chamorro", "nativeName": "Chamoru"},
  {"code": "ht", "iso639_2": "hat", "name": "Haitian", "nativeName": "Kreyòl ayisyen"},
  {"code": "la", "iso639_2": "lat", "name": "Latin", "nativeName": "latine"},
  {"code": "it", "iso639_2": "ita", "name": "Italian", "nativeName": "Italiano"},
  {"code": "hu", "iso639_2": "hun", "name": "Hungarian", "nativeName": "magyar"},
  {"code": "is", "iso639_2": "isl", "name": "Icelandic", "nativeName": "Íslenska"},
  {"code": "hi", "iso639_2": "hin", "name": "Hindi", "nativeName": "हिन्दी"},
  {"code": "id", "iso639_2": "ind", "name": "Indonesian", "nativeName": "Bahasa Indonesia"},
  {"code": "fa", "iso639_2": "fas", "name": "Persian (Farsi)", "nativeName": "فارسی"},
  {"code": "ku", "iso639_2": "kur", "name": "Kurdish", "nativeName": "Kurdî"},
  {"code": "ga", "iso639_2": "gle", "name": "Irish", "nativeName": "Gaeilge"},
  {"code": "gv", "iso639_2": "glv", "name": "Manx", "nativeName": "Gaelg"},
  {"code": "he", "iso639_2": "heb", "name": "Hebrew (modern)", "nativeName": "עברית"},
  {"code": "ja", "iso639_2": "jpn", "name": "Japanese", "nativeName": "日本語 (にほんご)"},
  {"code": "kk", "iso639_2": "kaz", "name": "Kazakh", "nativeName": "қазақ тілі"},
  {"code": "ky", "iso639_2": "kir", "name": "Kyrgyz", "nativeName": "Кыргызча"},
  {"code": "lo", "iso639_2": "lao", "name": "Lao", "nativeName": "ພາສາລາວ"},
  {"code": "lv", "iso639_2": "lav", "name": "Latvian", "nativeName": "latviešu valoda"},
  {"code": "st", "iso639_2": "sot", "name": "Southern Sotho", "nativeName": "Sesotho"},
  {"code": "lt", "iso639_2": "lit", "name": "Lithuanian", "nativeName": "lietuvių kalba"},
  {"code": "lb", "iso639_2": "ltz", "name": "Luxembourgish", "nativeName": "Lëtzebuergesch"},
  {"code": "mk", "iso639_2": "mkd", "name": "Macedonian", "nativeName": "македонски јазик"},
  {"code": "mg", "iso639_2": "mlg", "name": "Malagasy", "nativeName": "fiteny malagasy"},
  {"code": "ny", "iso639_2": "nya", "name": "Chichewa", "nativeName": "chiCheŵa"},
  {"code": "dv", "iso639_2": "div", "name": "Divehi", "nativeName": "ދިވެހި"},
  {"code": "mt", "iso639_2": "mlt", "name": "Maltese", "nativeName": "Malti"},
  {"code": "mh", "iso639_2": "mah", "name": "Marshallese", "nativeName": "Kajin M̧ajeļ"},
  {"code": "ro", "iso639_2": "ron", "name": "Romanian", "nativeName": "Română"},
  {"code": "mn", "iso639_2": "mon", "name": "Mongolian", "nativeName": "Монгол хэл"},
  {"code": "my", "iso639_2": "mya", "name": "Burmese", "nativeName": "ဗမာစာ"},
  {"code": "af", "iso639_2": "afr", "name": "Afrikaans", "nativeName": "Afrikaans"},
  {"code": "na", "iso639_2": "nau", "name": "Nauruan", "nativeName": "Dorerin Naoero"},
  {"code": "ne", "iso639_2": "nep", "name": "Nepali", "nativeName": "नेपाली"},
  {"code": "mi", "iso639_2": "mri", "name": "Māori", "nativeName": "te reo Māori"},
  {"code": "ko", "iso639_2": "kor", "name": "Korean", "nativeName": "한국어"},
  {"code": "ur", "iso639_2": "urd", "name": "Urdu", "nativeName": "اردو"},
  {"code": "pl", "iso639_2": "pol", "name": "Polish", "nativeName": "język polski"},
  {"code": "rw", "iso639_2": "kin", "name": "Kinyarwanda", "nativeName": "Ikinyarwanda"},
  {"code": "ta", "iso639_2": "tam", "name": "Tamil", "nativeName": "தமிழ்"},
  {"code": "sl", "iso639_2": "slv", "name": "Slovene", "nativeName": "slovenski jezik"},
  {"code": "so", "iso639_2": "som", "name": "Somali", "nativeName": "Soomaaliga"},
  {"code": "nr", "iso639_2": "nbl", "name": "Southern Ndebele", "nativeName": "isiNdebele"},
  {"code": "ss", "iso639_2": "ssw", "name": "Swati", "nativeName": "SiSwati"},
  {"code": "ts", "iso639_2": "tso", "name": "Tsonga", "nativeName": "Xitsonga"},
  {"code": "ve", "iso639_2": "ven", "name": "Venda", "nativeName": "Tshivenḓa"},
  {"code": "xh", "iso639_2": "xho", "name": "Xhosa", "nativeName": "isiXhosa"},
  {"code": "zu", "iso639_2": "zul", "name": "Zulu", "nativeName": "isiZulu"},
  {"code": "si", "iso639_2": "sin", "name": "Sinhalese", "nativeName": "සිංහල"},
  {"code": "tg", "iso639_2": "tgk", "name": "Tajik", "nativeName": "тоҷикӣ"},
  {"code": "th", "iso639_2": "tha", "name": "Thai", "nativeName": "ไทย"},
  {"code": "to", "iso639_2": "ton", "name": "Tonga (Tonga Islands)", "nativeName": "faka Tonga"},
  {"code": "uk", "iso639_2": "ukr", "name": "Ukrainian", "nativeName": "Українська"},
  {"code": "bi", "iso639_2": "bis", "name": "Bislama", "nativeName": "Bislama"},
  {"code": "vi", "iso639_2": "vie", "name": "Vietnamese", "nativeName": "Tiếng Việt"},
  {"code": "sn", "iso639_2": "sna", "name": "Shona", "nativeName": "chiShona"},
  {"code": "nd", "iso639_2": "nde", "name": "Northern Ndebele", "nativeName": "isiNdebele"}
];
